print("=" * 40)
times = ("Corinthians", "Palmeiras", "Santos", "Grêmio", "Cruzeiro", "Flamengo", "Vasco", "Chapecoense", "Atlético")
print(f"Os 5 primeiros são {times[:5]}")
print(f"Os 4 últimos são {times[-4:]}")
print(f"Times em ordem alfabética: {sorted(times)}")
print(f"O Chapecoense está na {times.index("Chapecoense") + 1} posição.")